name: Main Workflow

on:
  push:
    branches:
      - release

jobs:
  call-reusable-workflow:
    uses: kecetchup/learn_github_action/.github/workflows/reusable-workflow.yml
    with:
      string1: 'Hello, '
      string2: 'World'
