name: Reusable Workflow

on:
  workflow_call:
    inputs:
      string1:
        description: 'First input string'
        required: true
        type: string
      string2:
        description: 'Second input string'
        required: true
        type: string

jobs:
  combine-strings:
    runs-on: ubuntu-latest

    steps:
      - name: Combine strings
        run: echo "${{ inputs.string1 }}${{ inputs.string2 }}"
